name: build
on:
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Cache
        uses: actions/cache@v3.0.8
        with:
          path: ~/.npm
          key: buildCache
      - run: npm ci # instruct it to install the packages it depends on based on the package-lock file in the repository. The difference here is that npm
                    # ci is used in automated environments such as CI pipelines.
      - run: npm test -- --coverage
        env:
          CI: true
      - name: Upload code coverage
        uses: actions/upload-artifact@v3.1.0
        with:
          name: codecoverage
          path: coverage
      - name: build
        run: npm run build
      - name: Upload build files
        uses: actions/upload-artifact@v3.1.0
        with:
          name: build
          path: build
